import { Language, LanguageOption } from '../types/services';

export const LANGUAGE_OPTIONS: LanguageOption[] = [
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    flag: '🇺🇸'
  },
  {
    code: 'km',
    name: 'Khmer',
    nativeName: 'ខ្មែរ',
    flag: '🇰🇭'
  },
  {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸'
  },
  {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    flag: '🇫🇷'
  },
  {
    code: 'zh',
    name: 'Chinese',
    nativeName: '中文',
    flag: '🇨🇳'
  },
  {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    flag: '🇯🇵'
  },
  {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    flag: '🇰🇷'
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    flag: '🇻🇳'
  },
  {
    code: 'th',
    name: 'Thai',
    nativeName: 'ภาษาไทย',
    flag: '🇹🇭'
  }
];

export const DEFAULT_LANGUAGE: Language = 'en';

// UI Translations
export const UI_TRANSLATIONS = {
  en: {
    appTitle: 'NobiCode',
    appDescription: 'Enter your code below for AI analysis and improvement suggestions.',
    selectService: 'Select AI Service',
    selectModel: 'Select Model',
    selectLanguage: 'Select Language',
    codeInput: 'Your Code',
    codeInputPlaceholder: 'Enter your code here...',
    reviewButton: 'Review Code',
    analyzing: 'Analyzing...',
    cancelReview: 'Cancel',
    reviewCancelled: 'Review cancelled by user.',
    reviewResults: 'Review Results:',
    currentModel: 'Current Model',
    poweredBy: 'Powered by',
    geminiDocs: 'View Gemini API Docs',
    openrouterDocs: 'View OpenRouter API Docs',
    enterCodePrompt: 'Please enter some code to review.',
    readyToAnalyze: 'Ready to analyze your code. Click "Review Code" to start.',
    readyToAnalyzeSubtext: 'Click the review button to start analyzing your code',
    enterCodeToStart: 'Please enter some code in the editor above and click "Review Code" to start.',
    unknownError: 'An unknown error occurred.',
    // History-related translations
    history: 'History',
    reviewHistory: 'Review History',
    noHistory: 'No review history yet',
    noHistoryDescription: 'Your code review history will appear here after you analyze some code.',
    clearHistory: 'Clear All History',
    deleteItem: 'Delete',
    viewItem: 'View',
    confirmClearHistory: 'Are you sure you want to clear all history? This action cannot be undone.',
    confirmDeleteItem: 'Are you sure you want to delete this review?',
    historyItemsCount: 'items',
    showHistory: 'Show History',
    hideHistory: 'Hide History',
    // Warning notification translations
    warningTitle: 'History Storage Warning',
    warningMessage: 'You have {count} code reviews saved. When you reach 50 items, older reviews will be automatically removed.',
    exportButton: 'Export History',
    dismissButton: 'Got it',
    exportSuccess: 'History exported successfully!',
    exportError: 'Failed to export history. Please try again.',
    remaining: '{remaining} slots remaining',
    // Theme-related translations
    lightMode: 'Light',
    darkMode: 'Dark',
    switchToLight: 'Switch to light mode',
    switchToDark: 'Switch to dark mode',
    // New UI component translations
    pleaseWait: 'Please wait while we review your code',
    errorOccurred: 'An error occurred',
    tryAgain: 'Try Again',
    refreshPage: 'Refresh Page',
    errorHelp: 'If the problem persists, please check your internet connection and API configuration.',
    actions: 'Actions',
    copy: 'Copy',
    copied: 'Copied!',
    export: 'Export',
    exported: 'Exported!',
    share: 'Share',
    print: 'Print',
    newReview: 'New Review',
    // Streaming-related translations
    streamingMode: 'Streaming Mode',
    streamingDescription: 'Enable real-time response streaming for faster feedback',
    streamingEnabled: 'Streaming enabled',
    // Error message translations
    aiServiceNotInitialized: 'AI service is not initialized. Please ensure the API key is configured.',
    emptyCodeError: 'Cannot review empty code.',
    apiKeyInvalidError: 'API key is invalid or not configured. Please check your API key settings.',
    apiFailureError: 'Failed to get review from AI service',
    unknownApiError: 'Failed to get review from AI service due to unknown error.',
    // Quick Tips translations
    quickTips: 'Quick Tips:',
    quickTip1: 'Paste any code snippet for review',
    quickTip2: 'Supports multiple programming languages',
    quickTip3: 'Get detailed analysis and suggestions',
    quickTip4: 'Export results as Markdown',
    // Cancellation-related translations
    reviewCancelledTitle: 'Review Cancelled',
    reviewCancelledDescription: 'This is a partial review. The analysis was cancelled before completion.',
    streamingStatus: 'Streaming...',
    streamedStatus: 'Streamed',
    cancelledPartialStatus: 'Cancelled (Partial)',
    aiAnalyzingMessage: 'AI is analyzing your code...'
  },
  km: {
    appTitle: 'NobiCode',
    appDescription: 'សូម​បញ្ចូល​កូដ​របស់​អ្នក​ខាងក្រោម ដើម្បី​ឱ្យ AI ធ្វើការ​វិភាគ និង​ផ្ដល់​ជា​មតិកែលម្អ។',
    selectService: 'ជ្រើសរើស​សេវាកម្ម AI',
    selectModel: 'ជ្រើសរើស​ម៉ូដែល',
    selectLanguage: 'ជ្រើសរើស​ភាសា',
    codeInput: 'កូដ​របស់​អ្នក',
    codeInputPlaceholder: 'បញ្ចូល​​កូដ​របស់​អ្នក​នៅទីនេះ...',
    reviewButton: 'ពិនិត្យ​កូដ',
    analyzing: 'កំពុង​វិភាគ...',
    cancelReview: 'បោះបង់',
    reviewCancelled: 'ការពិនិត្យត្រូវបានបោះបង់ដោយអ្នកប្រើប្រាស់។',
    reviewResults: 'លទ្ធផលការវិភាគ',
    currentModel: 'ម៉ូដែល​បច្ចុប្បន្ន',
    poweredBy: 'ដំណើរការ​ដោយ',
    geminiDocs: 'មើល​ឯកសារ Gemini API',
    openrouterDocs: 'មើល​ឯកសារ OpenRouter API',
    enterCodePrompt: 'សូម​បញ្ចូល​កូដ​មួយចំនួន​ដើម្បី​ពិនិត្យ។',
    readyToAnalyze: 'ត្រៀមខ្លួន​ដើម្បី​វិភាគ​កូដ​របស់​អ្នក។ សូម​ចុច "ពិនិត្យ​កូដ" ដើម្បី​ចាប់ផ្ដើម។',
    enterCodeToStart: 'សូម​បញ្ចូល​​កូដ​មួយចំនួន​ទៅក្នុង​កម្មវិធី​កែសម្រួល​ខាងលើ ហើយ​ចុច "ពិនិត្យ​កូដ" ដើម្បី​ចាប់ផ្ដើម។',
    unknownError: 'មាន​កំហុស​មិនស្គាល់​មួយ​បាន​កើតឡើង។',
    // History-related translations
    history: 'ប្រវត្តិ',
    reviewHistory: 'ប្រវត្តិការពិនិត្យ',
    noHistory: 'មិនទាន់មានប្រវត្តិការពិនិត្យទេ',
    noHistoryDescription: 'ប្រវត្តិការពិនិត្យកូដរបស់អ្នកនឹងបង្ហាញនៅទីនេះ បន្ទាប់ពីអ្នកវិភាគកូដរួច។',
    clearHistory: 'លុបប្រវត្តិទាំងអស់',
    deleteItem: 'លុប',
    viewItem: 'មើល',
    confirmClearHistory: 'តើអ្នកប្រាកដថាចង់លុបប្រវត្តិទាំងអស់មែនទេ? សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ។',
    confirmDeleteItem: 'តើអ្នកប្រាកដថាចង់លុបការពិនិត្យនេះមែនទេ?',
    historyItemsCount: 'ធាតុ',
    showHistory: 'បង្ហាញប្រវត្តិ',
    hideHistory: 'លាក់ប្រវត្តិ',
    // Warning notification translations
    warningTitle: 'ការព្រមានផ្ទុកប្រវត្តិ',
    warningMessage: 'អ្នកមានការពិនិត្យកូដ {count} ដែលបានរក្សាទុក។ នៅពេលផ្ទុកដល់ 50 ធាតុ ការពិនិត្យចាស់ៗនឹងត្រូវបានលុបដោយស្វ័យប្រវត្តិ។',
    exportButton: 'ទាញយកប្រវត្តិ',
    dismissButton: 'យល់ហើយ',
    exportSuccess: 'ទាញយកប្រវត្តិបានជោគជ័យ!',
    exportError: 'បរាជ័យក្នុងការទាញយកប្រវត្តិ។ សូមព្យាយាមម្តងទៀត។',
    remaining: 'នៅសល់ {remaining} កន្លែង',
    // Theme-related translations
    lightMode: 'ភ្លឺ',
    darkMode: 'ងងឹត',
    switchToLight: 'ប្តូរទៅរបៀបភ្លឺ',
    switchToDark: 'ប្តូរទៅរបៀបងងឹត',
    // New UI component translations
    pleaseWait: 'សូមរង់ចាំ ខណៈពេលដែលយើងកំពុងពិនិត្យកូដរបស់អ្នក',
    errorOccurred: 'មានកំហុសកើតឡើង',
    tryAgain: 'ព្យាយាមម្តងទៀត',
    refreshPage: 'ផ្ទុកទំព័រឡើងវិញ',
    errorHelp: 'ប្រសិនបើបញ្ហានៅតែបន្ត សូមពិនិត្យការតភ្ជាប់អ៊ីនធឺណិត និងការកំណត់ API របស់អ្នក។',
    actions: 'សកម្មភាព',
    copy: 'ចម្លង',
    copied: 'បានចម្លង!',
    export: 'នាំចេញ',
    exported: 'បាននាំចេញ!',
    share: 'ចែករំលែក',
    print: 'បោះពុម្ព',
    newReview: 'ការពិនិត្យថ្មី',
    // Streaming-related translations
    streamingMode: 'បើកការស្ទ្រីម',
    streamingDescription: 'បើកការស្ទ្រីម ដើម្បីទទួលបានមតិកែលម្អលឿនជាងមុន',
    streamingEnabled: 'បានបើកការស្ទ្រីម',
    // Error message translations
    aiServiceNotInitialized: 'កម្មវិធី​តភ្ជាប់ AI មិនទាន់​ចាប់ផ្ដើម​ទេ។ សូម​ប្រាកដ​ថា API KEY ត្រូវ​បាន​កំណត់​។',
    emptyCodeError: 'មិនអាច​ពិនិត្យ​កូដ​ទទេ​បានទេ។',
    apiKeyInvalidError: 'API Key មិន​ត្រឹមត្រូវ ឬ​មិន​ត្រូវ​បានកំណត់​។ សូម​ពិនិត្យមើល​ការកំណត់​ API Key របស់​អ្នក។',
    apiFailureError: 'បរាជ័យ​ក្នុង​ការទទួល​បាន​ការពិនិត្យ​ពី​សេវាកម្ម AI',
    unknownApiError: 'បរាជ័យ​ក្នុង​ការទទួល​បាន​ការពិនិត្យ​ពី​សេវាកម្ម AI ដោយសារ​កំហុស​មិនស្គាល់​មូលហេតុ។',
    // Quick Tips translations
    quickTips: 'គន្លឹះរហ័ស៖',
    quickTip1: 'ដាក់កូដណាមួយសម្រាប់ការពិនិត្យ',
    quickTip2: 'គាំទ្រភាសាកម្មវិធីជាច្រើន',
    quickTip3: 'ទទួលបានការវិភាគលម្អិត និងផ្តល់យោបល់',
    quickTip4: 'ទាញយកលទ្ធផលជា Markdown',
    // Cancellation-related translations
    reviewCancelledTitle: 'ការពិនិត្យត្រូវបានបោះបង់',
    reviewCancelledDescription: 'នេះជាការពិនិត្យមួយផ្នែក។ ការវិភាគត្រូវបានបោះបង់មុនពេលបញ្ចប់។',
    streamingStatus: 'កំពុងស្ទ្រីម...',
    streamedStatus: 'បានស្ទ្រីម',
    cancelledPartialStatus: 'បានបោះបង់ (មួយផ្នែក)',
    aiAnalyzingMessage: 'AI កំពុងវិភាគកូដរបស់អ្នក...'
  },
  es: {
    appTitle: 'NobiCode',
    appDescription: 'Ingrese su código a continuación para el análisis de IA y sugerencias de mejora.',
    selectService: 'Seleccionar Servicio de IA',
    selectModel: 'Seleccionar Modelo',
    selectLanguage: 'Seleccionar Idioma',
    codeInput: 'Su Código',
    codeInputPlaceholder: 'Ingrese su código aquí...',
    reviewButton: 'Revisar Código',
    analyzing: 'Analizando...',
    cancelReview: 'Cancelar',
    reviewCancelled: 'Revisión cancelada por el usuario.',
    reviewResults: 'Resultados de la Revisión:',
    currentModel: 'Modelo Actual',
    poweredBy: 'Desarrollado por',
    geminiDocs: 'Ver Documentos de la API de Gemini',
    openrouterDocs: 'Ver Documentos de la API de OpenRouter',
    enterCodePrompt: 'Por favor, ingrese algo de código para revisar.',
    readyToAnalyze: 'Listo para analizar su código. Haga clic en "Revisar Código" para comenzar.',
    enterCodeToStart: 'Por favor, ingrese algo de código en el editor de arriba y haga clic en "Revisar Código" para comenzar.',
    unknownError: 'Ocurrió un error desconocido.',
    // History-related translations
    history: 'Historial',
    reviewHistory: 'Historial de Revisiones',
    noHistory: 'Aún no hay historial de revisiones',
    noHistoryDescription: 'Su historial de revisiones de código aparecerá aquí después de analizar algún código.',
    clearHistory: 'Limpiar Todo el Historial',
    deleteItem: 'Eliminar',
    viewItem: 'Ver',
    confirmClearHistory: '¿Está seguro de que desea limpiar todo el historial? Esta acción no se puede deshacer.',
    confirmDeleteItem: '¿Está seguro de que desea eliminar esta revisión?',
    historyItemsCount: 'elementos',
    showHistory: 'Mostrar Historial',
    hideHistory: 'Ocultar Historial',
    // Theme-related translations
    lightMode: 'Claro',
    darkMode: 'Oscuro',
    switchToLight: 'Cambiar a modo claro',
    switchToDark: 'Cambiar a modo oscuro',
    // Error message translations
    aiServiceNotInitialized: 'El servicio de IA no está inicializado. Por favor, asegúrese de que la clave API esté configurada.',
    emptyCodeError: 'No se puede revisar código vacío.',
    apiKeyInvalidError: 'La clave API es inválida o no está configurada. Por favor, verifique la configuración de su clave API.',
    apiFailureError: 'Error al obtener revisión del servicio de IA',
    unknownApiError: 'Error al obtener revisión del servicio de IA debido a un error desconocido.',
    // Quick Tips translations
    quickTips: 'Consejos Rápidos:',
    quickTip1: 'Pegue cualquier fragmento de código para revisar',
    quickTip2: 'Soporta múltiples lenguajes de programación',
    quickTip3: 'Obtenga análisis detallado y sugerencias',
    quickTip4: 'Exporte resultados como Markdown',
    // Cancellation-related translations
    reviewCancelledTitle: 'Revisión Cancelada',
    reviewCancelledDescription: 'Esta es una revisión parcial. El análisis fue cancelado antes de completarse.',
    streamingStatus: 'Transmitiendo...',
    streamedStatus: 'Transmitido',
    cancelledPartialStatus: 'Cancelado (Parcial)',
    aiAnalyzingMessage: 'IA está analizando su código...'
  },
  fr: {
    appTitle: 'NobiCode',
    appDescription: 'Entrez votre code ci-dessous pour l\'analyse IA et les suggestions d\'amélioration.',
    selectService: 'Sélectionner le Service IA',
    selectModel: 'Sélectionner le Modèle',
    selectLanguage: 'Sélectionner la Langue',
    codeInput: 'Votre Code',
    codeInputPlaceholder: 'Entrez votre code ici...',
    reviewButton: 'Réviser le Code',
    analyzing: 'Analyse en cours...',
    cancelReview: 'Annuler',
    reviewCancelled: 'Révision annulée par l\'utilisateur.',
    reviewResults: 'Résultats de la Révision :',
    currentModel: 'Modèle Actuel',
    poweredBy: 'Propulsé par',
    geminiDocs: 'Voir la Documentation de l\'API Gemini',
    openrouterDocs: 'Voir la Documentation de l\'API OpenRouter',
    enterCodePrompt: 'Veuillez entrer du code à réviser.',
    readyToAnalyze: 'Prêt à analyser votre code. Cliquez sur "Réviser le Code" pour commencer.',
    enterCodeToStart: 'Veuillez entrer du code dans l\'éditeur ci-dessus et cliquez sur "Réviser le Code" pour commencer.',
    unknownError: 'Une erreur inconnue est survenue.',
    // History-related translations
    history: 'Historique',
    reviewHistory: 'Historique des Révisions',
    noHistory: 'Aucun historique de révision pour le moment',
    noHistoryDescription: 'Votre historique de révision de code apparaîtra ici après avoir analysé du code.',
    clearHistory: 'Effacer Tout l\'Historique',
    deleteItem: 'Supprimer',
    viewItem: 'Voir',
    confirmClearHistory: 'Êtes-vous sûr de vouloir effacer tout l\'historique? Cette action ne peut pas être annulée.',
    confirmDeleteItem: 'Êtes-vous sûr de vouloir supprimer cette révision?',
    historyItemsCount: 'éléments',
    showHistory: 'Afficher l\'Historique',
    hideHistory: 'Masquer l\'Historique',
    // Theme-related translations
    lightMode: 'Clair',
    darkMode: 'Sombre',
    switchToLight: 'Passer au mode clair',
    switchToDark: 'Passer au mode sombre',
    // Error message translations
    aiServiceNotInitialized: 'Le service IA n\'est pas initialisé. Veuillez vous assurer que la clé API est configurée.',
    emptyCodeError: 'Impossible de réviser du code vide.',
    apiKeyInvalidError: 'La clé API est invalide ou non configurée. Veuillez vérifier les paramètres de votre clé API.',
    apiFailureError: 'Échec de l\'obtention de la révision du service IA',
    unknownApiError: 'Échec de l\'obtention de la révision du service IA en raison d\'une erreur inconnue.',
    // Quick Tips translations
    quickTips: 'Conseils Rapides :',
    quickTip1: 'Collez n\'importe quel extrait de code pour révision',
    quickTip2: 'Prend en charge plusieurs langages de programmation',
    quickTip3: 'Obtenez une analyse détaillée et des suggestions',
    quickTip4: 'Exportez les résultats en Markdown',
    // Cancellation-related translations
    reviewCancelledTitle: 'Révision Annulée',
    reviewCancelledDescription: 'Ceci est une révision partielle. L\'analyse a été annulée avant la fin.',
    streamingStatus: 'Diffusion en cours...',
    streamedStatus: 'Diffusé',
    cancelledPartialStatus: 'Annulé (Partiel)',
    aiAnalyzingMessage: 'L\'IA analyse votre code...'
  },
  zh: {
    appTitle: 'NobiCode',
    appDescription: '在下方输入您的代码，进行AI分析和改进建议。',
    selectService: '选择AI服务',
    selectModel: '选择模型',
    selectLanguage: '选择语言',
    codeInput: '您的代码',
    codeInputPlaceholder: '在此输入您的代码...',
    reviewButton: '审查代码',
    analyzing: '正在分析...',
    cancelReview: '取消',
    reviewCancelled: '用户已取消审查。',
    reviewResults: '审查结果：',
    currentModel: '当前模型',
    poweredBy: '技术支持',
    geminiDocs: '查看Gemini API文档',
    openrouterDocs: '查看OpenRouter API文档',
    enterCodePrompt: '请输入一些代码进行审查。',
    readyToAnalyze: '准备分析您的代码。点击“审查代码”开始。',
    enterCodeToStart: '请在上方编辑器中输入一些代码，然后点击“审查代码”开始。',
    unknownError: '发生未知错误。',
    // History-related translations
    history: '历史',
    reviewHistory: '审查历史',
    noHistory: '还没有审查历史',
    noHistoryDescription: '分析一些代码后，您的代码审查历史将显示在这里。',
    clearHistory: '清除所有历史',
    deleteItem: '删除',
    viewItem: '查看',
    confirmClearHistory: '您确定要清除所有历史吗？此操作无法撤消。',
    confirmDeleteItem: '您确定要删除此审查吗？',
    historyItemsCount: '项',
    showHistory: '显示历史',
    hideHistory: '隐藏历史',
    // Theme-related translations
    lightMode: '浅色',
    darkMode: '深色',
    switchToLight: '切换到浅色模式',
    switchToDark: '切换到深色模式',
    // Error message translations
    aiServiceNotInitialized: 'AI服务未初始化。请确保已配置API密钥。',
    emptyCodeError: '无法审查空代码。',
    apiKeyInvalidError: 'API密钥无效或未配置。请检查您的API密钥设置。',
    apiFailureError: '从AI服务获取审查失败',
    unknownApiError: '由于未知错误，从AI服务获取审查失败。',
    // Quick Tips translations
    quickTips: '快速提示：',
    quickTip1: '粘贴任何代码片段进行审查',
    quickTip2: '支持多种编程语言',
    quickTip3: '获得详细分析和建议',
    quickTip4: '将结果导出为Markdown',
    // Cancellation-related translations
    reviewCancelledTitle: '审查已取消',
    reviewCancelledDescription: '这是部分审查。分析在完成前被取消。',
    streamingStatus: '流式传输中...',
    streamedStatus: '已流式传输',
    cancelledPartialStatus: '已取消（部分）',
    aiAnalyzingMessage: 'AI正在分析您的代码...'
  },
  ja: {
    appTitle: 'NobiCode',
    appDescription: 'AI分析と改善提案のために、以下のコードを入力してください。',
    selectService: 'AIサービスを選択',
    selectModel: 'モデルを選択',
    selectLanguage: '言語を選択',
    codeInput: 'あなたのコード',
    codeInputPlaceholder: 'ここにコードを入力してください...',
    reviewButton: 'コードをレビュー',
    analyzing: '分析中...',
    cancelReview: 'キャンセル',
    reviewCancelled: 'ユーザーによってレビューがキャンセルされました。',
    reviewResults: 'レビュー結果：',
    currentModel: '現在のモデル',
    poweredBy: '提供元',
    geminiDocs: 'Gemini APIドキュメントを見る',
    openrouterDocs: 'OpenRouter APIドキュメントを見る',
    enterCodePrompt: 'レビューするコードを入力してください。',
    readyToAnalyze: 'コードを分析する準備ができました。「コードをレビュー」をクリックして開始します。',
    enterCodeToStart: '上記のエディタにコードを入力し、「コードをレビュー」をクリックして開始してください。',
    unknownError: '不明なエラーが発生しました。',
    // History-related translations
    history: '履歴',
    reviewHistory: 'レビュー履歴',
    noHistory: 'まだレビュー履歴がありません',
    noHistoryDescription: 'コードを分析すると、コードレビューの履歴がここに表示されます。',
    clearHistory: 'すべての履歴をクリア',
    deleteItem: '削除',
    viewItem: '表示',
    confirmClearHistory: 'すべての履歴をクリアしてもよろしいですか？この操作は元に戻せません。',
    confirmDeleteItem: 'このレビューを削除してもよろしいですか？',
    historyItemsCount: '項目',
    showHistory: '履歴を表示',
    hideHistory: '履歴を隠す',
    // Theme-related translations
    lightMode: 'ライト',
    darkMode: 'ダーク',
    switchToLight: 'ライトモードに切り替え',
    switchToDark: 'ダークモードに切り替え',
    // Error message translations
    aiServiceNotInitialized: 'AIサービスが初期化されていません。APIキーが設定されていることを確認してください。',
    emptyCodeError: '空のコードをレビューできません。',
    apiKeyInvalidError: 'APIキーが無効または設定されていません。APIキーの設定を確認してください。',
    apiFailureError: 'AIサービスからのレビュー取得に失敗しました',
    unknownApiError: '不明なエラーによりAIサービスからのレビュー取得に失敗しました。',
    // Quick Tips translations
    quickTips: 'クイックヒント：',
    quickTip1: 'レビュー用にコードスニペットを貼り付け',
    quickTip2: '複数のプログラミング言語をサポート',
    quickTip3: '詳細な分析と提案を取得',
    quickTip4: '結果をMarkdownとしてエクスポート',
    // Cancellation-related translations
    reviewCancelledTitle: 'レビューがキャンセルされました',
    reviewCancelledDescription: 'これは部分的なレビューです。分析は完了前にキャンセルされました。',
    streamingStatus: 'ストリーミング中...',
    streamedStatus: 'ストリーミング完了',
    cancelledPartialStatus: 'キャンセル済み（部分的）',
    aiAnalyzingMessage: 'AIがあなたのコードを分析しています...'
  },
  ko: {
    appTitle: 'NobiCode',
    appDescription: 'AI 분석 및 개선 제안을 위해 아래에 코드를 입력하세요.',
    selectService: 'AI 서비스 선택',
    selectModel: '모델 선택',
    selectLanguage: '언어 선택',
    codeInput: '귀하의 코드',
    codeInputPlaceholder: '여기에 코드를 입력하세요...',
    reviewButton: '코드 검토',
    analyzing: '분석 중...',
    cancelReview: '취소',
    reviewCancelled: '사용자가 검토를 취소했습니다.',
    reviewResults: '검토 결과:',
    currentModel: '현재 모델',
    poweredBy: '제공',
    geminiDocs: 'Gemini API 문서 보기',
    openrouterDocs: 'OpenRouter API 문서 보기',
    enterCodePrompt: '검토할 코드를 입력하세요.',
    readyToAnalyze: '코드 분석 준비 완료. "코드 검토"를 클릭하여 시작하세요.',
    enterCodeToStart: '위 편집기에 코드를 입력하고 "코드 검토"를 클릭하여 시작하세요.',
    unknownError: '알 수 없는 오류가 발생했습니다.',
    // History-related translations
    history: '기록',
    reviewHistory: '리뷰 기록',
    noHistory: '아직 리뷰 기록이 없습니다',
    noHistoryDescription: '코드를 분석하면 코드 리뷰 기록이 여기에 나타납니다.',
    clearHistory: '모든 기록 지우기',
    deleteItem: '삭제',
    viewItem: '보기',
    confirmClearHistory: '모든 기록을 지우시겠습니까? 이 작업은 되돌릴 수 없습니다.',
    confirmDeleteItem: '이 리뷰를 삭제하시겠습니까?',
    historyItemsCount: '항목',
    showHistory: '기록 보기',
    hideHistory: '기록 숨기기',
    // Theme-related translations
    lightMode: '라이트',
    darkMode: '다크',
    switchToLight: '라이트 모드로 전환',
    switchToDark: '다크 모드로 전환',
    // Error message translations
    aiServiceNotInitialized: 'AI 서비스가 초기화되지 않았습니다. API 키가 구성되어 있는지 확인하세요.',
    emptyCodeError: '빈 코드를 검토할 수 없습니다.',
    apiKeyInvalidError: 'API 키가 유효하지 않거나 구성되지 않았습니다. API 키 설정을 확인하세요.',
    apiFailureError: 'AI 서비스에서 검토를 가져오는 데 실패했습니다',
    unknownApiError: '알 수 없는 오류로 인해 AI 서비스에서 검토를 가져오는 데 실패했습니다.',
    // Quick Tips translations
    quickTips: '빠른 팁:',
    quickTip1: '검토를 위해 코드 스니펫을 붙여넣기',
    quickTip2: '여러 프로그래밍 언어 지원',
    quickTip3: '상세한 분석 및 제안 받기',
    quickTip4: '결과를 Markdown으로 내보내기',
    // Cancellation-related translations
    reviewCancelledTitle: '검토가 취소됨',
    reviewCancelledDescription: '이것은 부분 검토입니다. 분석이 완료되기 전에 취소되었습니다.',
    streamingStatus: '스트리밍 중...',
    streamedStatus: '스트리밍 완료',
    cancelledPartialStatus: '취소됨 (부분)',
    aiAnalyzingMessage: 'AI가 코드를 분석하고 있습니다...'
  },
  vi: {
    appTitle: 'NobiCode',
    appDescription: 'Nhập mã của bạn dưới đây để AI phân tích và đề xuất cải tiến.',
    selectService: 'Chọn Dịch vụ AI',
    selectModel: 'Chọn Mô hình',
    selectLanguage: 'Chọn Ngôn ngữ',
    codeInput: 'Mã của bạn',
    codeInputPlaceholder: 'Nhập mã của bạn tại đây...',
    reviewButton: 'Xem xét Mã',
    analyzing: 'Đang phân tích...',
    cancelReview: 'Hủy bỏ',
    reviewCancelled: 'Người dùng đã hủy bỏ việc xem xét.',
    reviewResults: 'Kết quả xem xét:',
    currentModel: 'Mô hình hiện tại',
    poweredBy: 'Được cung cấp bởi',
    geminiDocs: 'Xem Tài liệu API Gemini',
    openrouterDocs: 'Xem Tài liệu API OpenRouter',
    enterCodePrompt: 'Vui lòng nhập một số mã để xem xét.',
    readyToAnalyze: 'Sẵn sàng phân tích mã của bạn. Nhấp vào "Xem xét Mã" để bắt đầu.',
    enterCodeToStart: 'Vui lòng nhập một số mã vào trình chỉnh sửa ở trên và nhấp vào "Xem xét Mã" để bắt đầu.',
    unknownError: 'Đã xảy ra lỗi không xác định.',
    // History-related translations
    history: 'Lịch sử',
    reviewHistory: 'Lịch sử Đánh giá',
    noHistory: 'Chưa có lịch sử đánh giá',
    noHistoryDescription: 'Lịch sử đánh giá mã của bạn sẽ xuất hiện ở đây sau khi bạn phân tích một số mã.',
    clearHistory: 'Xóa Tất cả Lịch sử',
    deleteItem: 'Xóa',
    viewItem: 'Xem',
    confirmClearHistory: 'Bạn có chắc chắn muốn xóa tất cả lịch sử không? Hành động này không thể hoàn tác.',
    confirmDeleteItem: 'Bạn có chắc chắn muốn xóa đánh giá này không?',
    historyItemsCount: 'mục',
    showHistory: 'Hiện Lịch sử',
    hideHistory: 'Ẩn Lịch sử',
    // Theme-related translations
    lightMode: 'Sáng',
    darkMode: 'Tối',
    switchToLight: 'Chuyển sang chế độ sáng',
    switchToDark: 'Chuyển sang chế độ tối',
    // Error message translations
    aiServiceNotInitialized: 'Dịch vụ AI chưa được khởi tạo. Vui lòng đảm bảo khóa API đã được cấu hình.',
    emptyCodeError: 'Không thể xem xét mã trống.',
    apiKeyInvalidError: 'Khóa API không hợp lệ hoặc chưa được cấu hình. Vui lòng kiểm tra cài đặt khóa API của bạn.',
    apiFailureError: 'Không thể lấy đánh giá từ dịch vụ AI',
    unknownApiError: 'Không thể lấy đánh giá từ dịch vụ AI do lỗi không xác định.',
    // Quick Tips translations
    quickTips: 'Mẹo Nhanh:',
    quickTip1: 'Dán bất kỳ đoạn mã nào để xem xét',
    quickTip2: 'Hỗ trợ nhiều ngôn ngữ lập trình',
    quickTip3: 'Nhận phân tích chi tiết và đề xuất',
    quickTip4: 'Xuất kết quả dưới dạng Markdown',
    // Cancellation-related translations
    reviewCancelledTitle: 'Đánh giá đã bị hủy',
    reviewCancelledDescription: 'Đây là đánh giá một phần. Phân tích đã bị hủy trước khi hoàn thành.',
    streamingStatus: 'Đang phát trực tuyến...',
    streamedStatus: 'Đã phát trực tuyến',
    cancelledPartialStatus: 'Đã hủy (Một phần)',
    aiAnalyzingMessage: 'AI đang phân tích mã của bạn...'
  },
  th: {
    appTitle: 'NobiCode',
    appDescription: 'ป้อนโค้ดของคุณด้านล่างสำหรับการวิเคราะห์ AI และข้อเสนอแนะในการปรับปรุง',
    selectService: 'เลือกบริการ AI',
    selectModel: 'เลือกรุ่น',
    selectLanguage: 'เลือกภาษา',
    codeInput: 'โค้ดของคุณ',
    codeInputPlaceholder: 'ป้อนโค้ดของคุณที่นี่...',
    reviewButton: 'ตรวจสอบโค้ด',
    analyzing: 'กำลังวิเคราะห์...',
    cancelReview: 'ยกเลิก',
    reviewCancelled: 'ผู้ใช้ได้ยกเลิกการตรวจสอบ',
    reviewResults: 'ผลการตรวจสอบ:',
    currentModel: 'รุ่นปัจจุบัน',
    poweredBy: 'ขับเคลื่อนโดย',
    geminiDocs: 'ดูเอกสาร Gemini API',
    openrouterDocs: 'ดูเอกสาร OpenRouter API',
    enterCodePrompt: 'โปรดป้อนโค้ดบางส่วนเพื่อตรวจสอบ',
    readyToAnalyze: 'พร้อมที่จะวิเคราะห์โค้ดของคุณแล้ว คลิก "ตรวจสอบโค้ด" เพื่อเริ่มต้น',
    enterCodeToStart: 'โปรดป้อนโค้ดบางส่วนในตัวแก้ไขด้านบนแล้วคลิก "ตรวจสอบโค้ด" เพื่อเริ่มต้น',
    unknownError: 'เกิดข้อผิดพลาดที่ไม่รู้จัก',
    // History-related translations
    history: 'ประวัติ',
    reviewHistory: 'ประวัติการตรวจสอบ',
    noHistory: 'ยังไม่มีประวัติการตรวจสอบ',
    noHistoryDescription: 'ประวัติการตรวจสอบโค้ดของคุณจะปรากฏที่นี่หลังจากที่คุณวิเคราะห์โค้ดบางส่วน',
    clearHistory: 'ล้างประวัติทั้งหมด',
    deleteItem: 'ลบ',
    viewItem: 'ดู',
    confirmClearHistory: 'คุณแน่ใจหรือไม่ว่าต้องการล้างประวัติทั้งหมด? การดำเนินการนี้ไม่สามารถยกเลิกได้',
    confirmDeleteItem: 'คุณแน่ใจหรือไม่ว่าต้องการลบการตรวจสอบนี้?',
    historyItemsCount: 'รายการ',
    showHistory: 'แสดงประวัติ',
    hideHistory: 'ซ่อนประวัติ',
    // Theme-related translations
    lightMode: 'สว่าง',
    darkMode: 'มืด',
    switchToLight: 'เปลี่ยนเป็นโหมดสว่าง',
    switchToDark: 'เปลี่ยนเป็นโหมดมืด',
    // Error message translations
    aiServiceNotInitialized: 'บริการ AI ยังไม่ได้เริ่มต้น โปรดตรวจสอบให้แน่ใจว่าได้กำหนดค่า API key แล้ว',
    emptyCodeError: 'ไม่สามารถตรวจสอบโค้ดที่ว่างเปล่าได้',
    apiKeyInvalidError: 'API key ไม่ถูกต้องหรือยังไม่ได้กำหนดค่า โปรดตรวจสอบการตั้งค่า API key ของคุณ',
    apiFailureError: 'ไม่สามารถรับการตรวจสอบจากบริการ AI ได้',
    unknownApiError: 'ไม่สามารถรับการตรวจสอบจากบริการ AI ได้เนื่องจากข้อผิดพลาดที่ไม่รู้จัก',
    // Quick Tips translations
    quickTips: 'เคล็ดลับด่วน:',
    quickTip1: 'วางโค้ดส่วนใดก็ได้เพื่อตรวจสอบ',
    quickTip2: 'รองรับภาษาโปรแกรมหลายภาษา',
    quickTip3: 'รับการวิเคราะห์โดยละเอียดและข้อเสนอแนะ',
    quickTip4: 'ส่งออกผลลัพธ์เป็น Markdown',
    // Cancellation-related translations
    reviewCancelledTitle: 'การตรวจสอบถูกยกเลิก',
    reviewCancelledDescription: 'นี่เป็นการตรวจสอบบางส่วน การวิเคราะห์ถูกยกเลิกก่อนที่จะเสร็จสิ้น',
    streamingStatus: 'กำลังสตรีม...',
    streamedStatus: 'สตรีมแล้ว',
    cancelledPartialStatus: 'ยกเลิกแล้ว (บางส่วน)',
    aiAnalyzingMessage: 'AI กำลังวิเคราะห์โค้ดของคุณ...'
  }
};
